---
projects:
  - id: twitter
    name: Read Twitter
    at:
      - home
      - work
  - id: work
    name: Do work
    at:
      - work
  - id: nowork
    name: "Don't do work"
    at:
      - home
counts: {}
