[package]
name = "whatnow"
version = "0.1.0"
authors = ["***Realname*** ***Lastname*** <***redacted.email@redacted.nope***>"]
edition = "2018"

[dependencies]
failure = "*"
rand = "*"
serde = "*"
serde_derive = "*"
serde_yaml = "*"
